[[news]]
date = ""
content = "[Tiankai Hang](https://tiankaihang.github.io/)"

[[news]]
date = ""
content = "[Jinming Liu](https://jmliu206.github.io/jmliu.github.io/)"

[[news]]
date = ""
content = "[Zongyu Guo](https://zongyuguo.github.io/)"

[[news]]
date = ""
content = "Ziqi Yin"

[[news]]
date = ""
content = "[Yanhui Wang](https://scholar.google.com/citations?user=Trsj4pQAAAAJ&hl=zh-CN)"

[[news]]
date = ""
content = "[Wenming Weng](https://scholar.google.com/citations?user=9xtKbMMAAAAJ&hl=en)"

[[news]]
date = ""
content = "[Zhipeng Huang](https://scholar.google.com/citations?hl=en&user=_fnuIHUAAAAJ&view_op=list_works&sortby=pubdate)"

[[news]]
date = ""
content = "[Shaojin Wu](https://scholar.google.com/citations?user=9ER6nVkAAAAJ&hl=en)"
